In [17]:
from fastai.tabular.all import *

In [18]:
learn_win_loss = load_learner("./20221015_model_reg")

In [19]:
# load rankings of all teams
rankings = pd.read_csv('./datasets/fifa_ranking-2022-08-25.csv')
rankings = rankings.loc[:,['rank', 'country_full', 'country_abrv', 'rank_date']]
rankings.country_full.replace("^IR Iran*", "Iran", regex=True, inplace=True)
rankings['rank_date'] = pd.to_datetime(rankings['rank_date'])

rankings = rankings.set_index(['rank_date'])\
                    .groupby(['country_full'],group_keys = False)\
                    .resample('D').first()\
                    .fillna(method='ffill')\
                    .reset_index()
rankings.tail()

         rank_date   rank country_full country_abrv
2285125 2022-08-21  123.0     Zimbabwe          ZIM
2285126 2022-08-22  123.0     Zimbabwe          ZIM
2285127 2022-08-23  123.0     Zimbabwe          ZIM
2285128 2022-08-24  123.0     Zimbabwe          ZIM
2285129 2022-08-25  123.0     Zimbabwe          ZIM

In [20]:
# cleanup WM 18 matches
world_cup18 = pd.read_csv("./datasets/World Cup 2018 Dataset.csv")
world_cup18 = world_cup18.loc[:, ['Team', 'Group', 'First match \nagainst', 'Second match\n against', 'Third match\n against']]
world_cup18 = world_cup18.dropna(how='all')
world_cup18 = world_cup18.replace({"IRAN": "Iran", 
                               "Costarica": "Costa Rica", 
                               "Porugal": "Portugal", 
                               "Columbia": "Colombia", 
                               "Korea" : "Korea Republic"})
world_cup18 = world_cup18.set_index('Team')
world_cup18.head()

,Group,First match \nagainst,Second match\n against,Third match\n against
Team,,,,
Russia,A,Saudi Arabia,Egypt,Uruguay
Saudi Arabia,A,Russia,Uruguay,Egypt
Egypt,A,Uruguay,Russia,Saudi Arabia
Uruguay,A,Egypt,Saudi Arabia,Russia
Portugal,B,Spain,Morocco,Iran

In [21]:
# define rankings at the time of the WM
world_cup_rankings = rankings.loc[(rankings['rank_date'] == rankings['rank_date'].max()) & 
                                    rankings['country_full'].isin(world_cup18.index.unique())]
world_cup_rankings = world_cup_rankings.set_index(['country_full'])
world_cup_rankings

                rank_date  rank country_abrv
country_full
Argentina      2022-08-25   3.0          ARG
Australia      2022-08-25  39.0          AUS
Belgium        2022-08-25   2.0          BEL
Brazil         2022-08-25   1.0          BRA
Colombia       2022-08-25  17.0          COL
Costa Rica     2022-08-25  34.0          CRC
Croatia        2022-08-25  15.0          CRO
Denmark        2022-08-25  10.0          DEN
Egypt          2022-08-25  40.0          EGY
England        2022-08-25   5.0          ENG
France         2022-08-25   4.0          FRA
Germany        2022-08-25  11.0          GER
Iceland        2022-08-25  63.0          ISL
Iran           2022-08-25  22.0          IRN
Japan          2022-08-25  24.0          JPN
Korea Republic 2022-08-25  28.0          KOR
Mexico         2022-08-25  12.0          MEX
Morocco        2022-08-25  23.0          MAR
Nigeria        2022-08-25  31.0          NGA
Panama         2022-08-25  61.0          PAN
Peru           2022-08-25  21.0          PER
Poland         2022-08-25  26.0          POL
Portugal       2022-08-25   9.0          POR
Russia         2022-08-25  35.0          RUS
Saudi Arabia   2022-08-25  53.0          KSA
Senegal        2022-08-25  18.0          SEN
Serbia         2022-08-25  25.0          SRB
Spain          2022-08-25   6.0          ESP
Sweden         2022-08-25  20.0          SWE
Switzerland    2022-08-25  16.0          SUI
Tunisia        2022-08-25  30.0          TUN
Uruguay        2022-08-25  13.0          URU

In [22]:
wm18_results = pd.read_csv('./datasets/WM2018Result.csv')
wm18_results = wm18_results.loc[:,["HomeTeam", "AwayTeam", "Group", "HomeTeamScore", "AwayTeamScore"]]
wm18_results = wm18_results[wm18_results.Group.isnull() == False]

wm18_results["is_won"] = (wm18_results.HomeTeamScore - wm18_results.AwayTeamScore) > 0

wm18_results

,HomeTeam,AwayTeam,Group,HomeTeamScore,AwayTeamScore,is_won
0,Russia,Saudi Arabia,Group A,5,0,True
1,Egypt,Uruguay,Group A,0,1,False
2,Morocco,Iran,Group B,0,1,False
3,Portugal,Spain,Group B,3,3,False
4,France,Australia,Group C,2,1,True
5,Argentina,Iceland,Group D,1,1,False
6,Peru,Denmark,Group C,0,1,False
7,Croatia,Nigeria,Group D,2,0,True
8,Costa Rica,Serbia,Group E,0,1,False
9,Germany,Mexico,Group F,0,1,False
10,Brazil,Switzerland,Group E,1,1,False
11,Sweden,Korea Republic,Group F,1,0,True
12,Belgium,Panama,Group G,3,0,True
13,Tunisia,England,Group G,1,2,False
14,Colombia,Japan,Group H,1,2,False
15,Poland,Senegal,Group H,1,2,False
16,Russia,Egypt,Group A,3,1,True
17,Portugal,Morocco,Group B,1,0,True
18,Uruguay,Saudi Arabia,Group A,1,0,True
19,Iran,Spain,Group B,0,1,False
20,Denmark,Australia,Group C,1,1,False
21,France,Peru,Group C,1,0,True
22,Argentina,Croatia,Group D,0,3,False
23,Brazil,Costa Rica,Group E,2,0,True
24,Nigeria,Iceland,Group D,2,0,True
25,Serbia,Switzerland,Group E,1,2,False
26,Belgium,Tunisia,Group G,5,2,True
27,Korea Republic,Mexico,Group F,1,2,False
28,Germany,Sweden,Group F,2,1,True
29,England,Panama,Group G,6,1,True
30,Japan,Senegal,Group H,2,2,False
31,Poland,Colombia,Group H,0,3,False
32,Uruguay,Russia,Group A,3,0,True
33,Saudi Arabia,Egypt,Group A,2,1,True
34,Iran,Portugal,Group B,1,1,False
35,Spain,Morocco,Group B,2,2,False
36,Denmark,France,Group C,0,0,False
37,Australia,Peru,Group C,0,2,False
38,Nigeria,Argentina,Group D,1,2,False
39,Iceland,Croatia,Group D,1,2,False
40,Mexico,Sweden,Group F,0,3,False
41,Korea Republic,Germany,Group F,2,0,True
42,Serbia,Brazil,Group E,0,2,False
43,Switzerland,Costa Rica,Group E,2,2,False
44,Japan,Poland,Group H,0,1,False
45,Senegal,Colombia,Group H,0,1,False
46,Panama,Tunisia,Group G,1,2,False
47,England,Belgium,Group G,0,1,False

In [58]:
from itertools import combinations

def getPoints(home_score, away_score, home_score_pred, away_score_pred): 
    if home_score == home_score_pred and away_score == away_score_pred:
        return 4
    elif home_score == away_score and home_score_pred == away_score_pred:
        return 2
    elif home_score - away_score == home_score_pred - away_score_pred:
        return 3
    elif home_score > away_score and home_score_pred > away_score_pred:
        return 2
    elif home_score < away_score and home_score_pred < away_score_pred:
        return 2
    else:
        return 0

wm18_results['home_score_pred'] = 0
wm18_results['home_score_prob'] = 0.0
wm18_results['away_score_pred'] = 0
wm18_results['away_score_prob'] = 0.0
wm18_results['tipp_points'] = 0

for index, item in wm18_results.iterrows():
    home = item['HomeTeam']
    away = item['AwayTeam']

    row = pd.DataFrame(np.array([[]]))
    home_rank = world_cup_rankings.loc[home, 'rank']
    opp_rank = world_cup_rankings.loc[away, 'rank']

    row['average_rank'] = (home_rank + opp_rank) / 2
    row['rank_difference'] = home_rank - opp_rank
    row['is_stake'] = True
    row['home_team'] = home
    row['away_team'] = away
    row['is_won'] = item['is_won']

    dl = learn_win_loss.dls.test_dl(row, bs=1)
    preds, _ = learn_win_loss.get_preds(dl=dl)

    # print(preds.numpy(), home, away)
    home_score_prob = preds.numpy()[0][0]
    away_score_prob = preds.numpy()[0][1]
    wm18_results.at[index, 'home_score_prob'] = home_score_prob
    wm18_results.at[index, 'home_score_pred'] = home_score_prob.round(0)
    wm18_results.at[index, 'away_score_prob'] = away_score_prob
    wm18_results.at[index, 'away_score_pred'] = away_score_prob.round(0)
    wm18_results.at[index, 'tipp_points'] = getPoints(item.HomeTeamScore, item.AwayTeamScore, home_score_prob.round(0), away_score_prob.round(0))

wm18_results

,HomeTeam,AwayTeam,Group,HomeTeamScore,AwayTeamScore,is_won,home_score_pred,home_score_prob,away_score_pred,away_score_prob,tipp_points
0,Russia,Saudi Arabia,Group A,5,0,True,2,2.404817,0,0.431003,2
1,Egypt,Uruguay,Group A,0,1,False,1,0.644541,2,2.088127,3
2,Morocco,Iran,Group B,0,1,False,1,0.695365,1,1.354071,0
3,Portugal,Spain,Group B,3,3,False,1,0.758356,2,1.532779,0
4,France,Australia,Group C,2,1,True,3,2.717791,0,0.385791,2
5,Argentina,Iceland,Group D,1,1,False,1,0.800640,1,1.202904,4
6,Peru,Denmark,Group C,0,1,False,1,0.637869,1,1.301889,0
7,Croatia,Nigeria,Group D,2,0,True,2,2.207614,1,0.554852,2
8,Costa Rica,Serbia,Group E,0,1,False,1,0.636390,1,1.453297,0
9,Germany,Mexico,Group F,0,1,False,1,0.689542,2,1.607236,3
10,Brazil,Switzerland,Group E,1,1,False,1,0.698946,1,1.322923,4
11,Sweden,Korea Republic,Group F,1,0,True,2,2.258950,0,0.403479,2
12,Belgium,Panama,Group G,3,0,True,3,2.669062,0,0.459646,4
13,Tunisia,England,Group G,1,2,False,1,0.632855,2,1.596013,4
14,Colombia,Japan,Group H,1,2,False,1,0.774449,2,1.747401,4
15,Poland,Senegal,Group H,1,2,False,1,0.623080,1,1.316856,0
16,Russia,Egypt,Group A,3,1,True,2,2.265820,0,0.438264,3
17,Portugal,Morocco,Group B,1,0,True,2,2.325119,0,0.414278,2
18,Uruguay,Saudi Arabia,Group A,1,0,True,3,3.063158,1,0.500274,2
19,Iran,Spain,Group B,0,1,False,1,0.693983,2,1.856200,3
20,Denmark,Australia,Group C,1,1,False,1,0.659508,1,1.392204,4
21,France,Peru,Group C,1,0,True,2,2.344485,0,0.392640,2
22,Argentina,Croatia,Group D,0,3,False,1,0.746448,1,1.387900,0
23,Brazil,Costa Rica,Group E,2,0,True,3,2.742869,1,0.508413,3
24,Nigeria,Iceland,Group D,2,0,True,2,2.349022,0,0.460418,4
25,Serbia,Switzerland,Group E,1,2,False,1,0.631610,1,1.419315,0
26,Belgium,Tunisia,Group G,5,2,True,2,2.309489,0,0.472438,2
27,Korea Republic,Mexico,Group F,1,2,False,1,0.635650,1,1.492585,0
28,Germany,Sweden,Group F,2,1,True,3,2.620363,1,0.611357,2
29,England,Panama,Group G,6,1,True,3,2.748183,0,0.416176,2
30,Japan,Senegal,Group H,2,2,False,1,0.557491,1,1.412474,2
31,Poland,Colombia,Group H,0,3,False,1,0.545233,1,1.301639,0
32,Uruguay,Russia,Group A,3,0,True,3,2.631649,1,0.590943,2
33,Saudi Arabia,Egypt,Group A,2,1,True,2,2.279825,1,0.533775,4
34,Iran,Portugal,Group B,1,1,False,1,0.787339,2,1.609473,0
35,Spain,Morocco,Group B,2,2,False,1,0.693636,1,1.205868,2
36,Denmark,France,Group C,0,0,False,0,0.480240,1,1.458678,0
37,Australia,Peru,Group C,0,2,False,1,0.592933,1,1.369870,0
38,Nigeria,Argentina,Group D,1,2,False,1,0.666547,2,1.746436,4
39,Iceland,Croatia,Group D,1,2,False,1,0.682050,2,1.600534,4
40,Mexico,Sweden,Group F,0,3,False,1,0.684446,1,1.468815,0
41,Korea Republic,Germany,Group F,2,0,True,2,2.393322,1,0.507958,2
42,Serbia,Brazil,Group E,0,2,False,1,0.629326,2,2.106770,2
43,Switzerland,Costa Rica,Group E,2,2,False,1,0.759250,2,1.535349,0
44,Japan,Poland,Group H,0,1,False,1,0.625978,2,1.643562,3
45,Senegal,Colombia,Group H,0,1,False,1,0.546127,1,1.179414,0
46,Panama,Tunisia,Group G,1,2,False,1,0.727152,1,1.300712,0
47,England,Belgium,Group G,0,1,False,1,0.798451,1,1.438830,0

In [59]:
wm18_results.tipp_points.sum() / wm18_results.tipp_points.count()

1.8333333333333333

In [60]:
wm18_results[wm18_results.tipp_points == 4].tipp_points.count()

10

In [61]:
wm18_results[wm18_results.tipp_points == 3].tipp_points.count()

6

In [62]:
wm18_results[wm18_results.tipp_points == 2].tipp_points.count()

15

In [63]:
wm18_results[wm18_results.tipp_points == 0].tipp_points.count()

17

In [68]:
wm18_results[(wm18_results.tipp_points == 0) & (wm18_results.HomeTeamScore == wm18_results.AwayTeamScore)].tipp_points.count()

4